In [1]:
from google.colab import files
uploaded = files.upload()

Saving WA_Fn-UseC_-Telco-Customer-Churn.csv to WA_Fn-UseC_-Telco-Customer-Churn.csv

In [58]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import TensorDataset, DataLoader
import torch.optim as optim
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [27]:
df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [29]:
#data cleaning
#label encoding
cols = ['OnlineSecurity', 'MultipleLines', 'InternetService', 'Contract',
        'PaymentMethod','gender', 'Partner', 'Dependents', 'PhoneService', 'DeviceProtection',
         'TechSupport','StreamingTV', 'StreamingMovies', 'Dependents', 'PaperlessBilling', 'Churn',
        'OnlineBackup'
        ]
for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
#data fill
cols = [
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies"
]

for i in cols:
    mode_values = df[i].mode()

    if not mode_values.empty:
        df[i] = df[i].fillna(mode_values.iloc[0])
    else:
        print(f"{i} contains only null values")

In [34]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df["TotalCharges"] = df["TotalCharges"].fillna(0)

print(df["TotalCharges"].dtype)

float64

In [35]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,2,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,3,56.95,1889.50,0
2,3668-QPYBK,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,3,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,0,42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,2,70.70,151.65,1

In [36]:
x = df.drop(['Churn','customerID'], axis = 1)
y = df['Churn']

In [37]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [38]:
X_train_tensor = torch.tensor(x_train_scaled, dtype = torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype = torch.float32).view(-1,1)
X_test_tensor = torch.tensor(x_test_scaled, dtype = torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype = torch.float32).view(-1,1)

In [41]:
# Create Tensor datasets
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

# Create DataLoaders
train_loader = DataLoader(
    train_dataset, batch_size=32, shuffle=True
)

test_loader = DataLoader(
    test_dataset, batch_size=32, shuffle=False
)

In [ ]:
#model initia lize

In [52]:
class ANN(nn.Module):
  def __init__(self):
    super(ANN, self).__init__()
    self.model = nn.Sequential(
        #1st hidden layer
        nn.Linear(X_train.shape[1],32),
        nn.ReLU(),
        #2nd hidden layer
        nn.Linear(32,32),
        nn.ReLU(),
        #output layer
        nn.Linear(32,1)
    )
  def forward (self,x):
    return self.model(x)

In [53]:
model = ANN()
criterion = nn.BCEWithLogitsLoss()

optimizer = optim.Adam(
    model.parameters(),lr=0.001,weight_decay=1e-4
)

In [54]:
#Train the model
epochs = 100
train_losses = []
val_losses = []
for epoch in range(epochs):
  model.train()
  running_loss =0.0
  for xb,yb in train_loader:
    optimizer.zero_grad()
    output = model(xb)
    loss = criterion(output,yb)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
  epoch_train_loss = running_loss / len(train_loader)
  train_losses.append(epoch_train_loss)
  #validation state
  model.eval()
  running_val_loss =0.0
  with torch.no_grad():
     for xb,yb in test_loader:
          output = model(xb)
          loss = criterion(output,yb)
          running_val_loss += loss.item()
     epoch_val_loss = running_val_loss / len(test_loader)
     val_losses.append(epoch_val_loss)
     print(f"epoch{epoch+1}/{epochs}=> train loss = {epoch_train_loss} & vall loss = {epoch_val_loss}")

epoch1/100=> train loss = 0.49680352143648654 & vall loss = 0.42791912025875517
epoch2/100=> train loss = 0.4302477202678131 & vall loss = 0.418315894736184
epoch3/100=> train loss = 0.42444059362182507 & vall loss = 0.41303789085812037
epoch4/100=> train loss = 0.4219659610656695 & vall loss = 0.4112573352124956
epoch5/100=> train loss = 0.4192009649034274 & vall loss = 0.407205628686481
epoch6/100=> train loss = 0.41557385827188437 & vall loss = 0.40482860505580903
epoch7/100=> train loss = 0.4160088245141304 & vall loss = 0.4029580016930898
epoch8/100=> train loss = 0.41090173320581685 & vall loss = 0.4052595933278402
epoch9/100=> train loss = 0.41165243510135824 & vall loss = 0.40542309284210204
epoch10/100=> train loss = 0.40695375187248833 & vall loss = 0.40403598215844894
epoch11/100=> train loss = 0.4056056914693218 & vall loss = 0.40497801237636144
epoch12/100=> train loss = 0.40560566974898515 & vall loss = 0.40512024694018894
epoch13/100=> train loss = 0.4048359765339706 & vall loss = 0.40879564815097386
epoch14/100=> train loss = 0.4056156480548072 & vall loss = 0.4074067691961924
epoch15/100=> train loss = 0.40136319398880005 & vall loss = 0.40655318829748366
epoch16/100=> train loss = 0.39930384096789495 & vall loss = 0.4049235549237993
epoch17/100=> train loss = 0.4025371302824236 & vall loss = 0.40515418185128105
epoch18/100=> train loss = 0.3994297976210966 & vall loss = 0.408577909734514
epoch19/100=> train loss = 0.39751183843545324 & vall loss = 0.4072614120112525
epoch20/100=> train loss = 0.39605746700265315 & vall loss = 0.40635150074958803
epoch21/100=> train loss = 0.39452078980577865 & vall loss = 0.40865246189965143
epoch22/100=> train loss = 0.39287529085989054 & vall loss = 0.40901336471239724
epoch23/100=> train loss = 0.38963397318697246 & vall loss = 0.4100969347688887
epoch24/100=> train loss = 0.388848556047779 & vall loss = 0.40741546087794833
epoch25/100=> train loss = 0.3893262992302577 & vall loss = 0.4120728108617995
epoch26/100=> train loss = 0.3894525320179718 & vall loss = 0.41095645162794325
epoch27/100=> train loss = 0.38581349856435915 & vall loss = 0.41131667362319096
epoch28/100=> train loss = 0.3863500198401974 & vall loss = 0.41665622194608054
epoch29/100=> train loss = 0.3845705713255931 & vall loss = 0.41691605713632374
epoch30/100=> train loss = 0.38186789771257823 & vall loss = 0.4173027343220181
epoch31/100=> train loss = 0.3873306498520792 & vall loss = 0.4206103556685977
epoch32/100=> train loss = 0.3840970487917884 & vall loss = 0.4212586541970571
epoch33/100=> train loss = 0.3798787100503674 & vall loss = 0.4194164256254832
epoch34/100=> train loss = 0.3777837475477639 & vall loss = 0.4197857479254405
epoch35/100=> train loss = 0.3804097136871963 & vall loss = 0.42189307808876036
epoch36/100=> train loss = 0.3755986266216989 & vall loss = 0.42363161312209235
epoch37/100=> train loss = 0.38212369660199696 & vall loss = 0.4251571602291531
epoch38/100=> train loss = 0.3748365761028171 & vall loss = 0.4217437379890018
epoch39/100=> train loss = 0.3795186135560106 & vall loss = 0.4284167872534858
epoch40/100=> train loss = 0.37458051968429046 & vall loss = 0.42249819570117525
epoch41/100=> train loss = 0.37231634153147874 & vall loss = 0.4269755237632328
epoch42/100=> train loss = 0.37024022445166854 & vall loss = 0.4317201700475481
epoch43/100=> train loss = 0.3721257393474633 & vall loss = 0.4325134065416124
epoch44/100=> train loss = 0.3686065128715025 & vall loss = 0.43297405044237774
epoch45/100=> train loss = 0.36949072416219336 & vall loss = 0.43007519443829856
epoch46/100=> train loss = 0.37636155984495995 & vall loss = 0.4353542579544915
epoch47/100=> train loss = 0.36621277101632566 & vall loss = 0.4380609605047438
epoch48/100=> train loss = 0.3658864634521937 & vall loss = 0.4342398034201728
epoch49/100=> train loss = 0.3646719837087696 & vall loss = 0.44061564670668707
epoch50/100=> train loss = 0.3647871758304747 & vall loss = 0.4361793292893304
epoch51/100=> train loss = 0.36344395072783453 & vall loss = 0.43979948163032534
epoch52/100=> train loss = 0.3633329859897915 & vall loss = 0.4390892611609565
epoch53/100=> train loss = 0.3608072320956968 & vall loss = 0.4426078842745887
epoch54/100=> train loss = 0.3653587274632211 & vall loss = 0.4409586952792274
epoch55/100=> train loss = 0.3650771688017468 & vall loss = 0.4419435322284698
epoch56/100=> train loss = 0.3577893953875633 & vall loss = 0.4485102799203661
epoch57/100=> train loss = 0.3592570663171973 & vall loss = 0.4465483254856534
epoch58/100=> train loss = 0.35869539592225674 & vall loss = 0.4517974820401933
epoch59/100=> train loss = 0.3567218808299404 & vall loss = 0.44485735297203066
epoch60/100=> train loss = 0.357450963413648 & vall loss = 0.4509665264023675
epoch61/100=> train loss = 0.35634980169729996 & vall loss = 0.4497861716482374
epoch62/100=> train loss = 0.35508418243146883 & vall loss = 0.4554357389609019
epoch63/100=> train loss = 0.36266319630509714 & vall loss = 0.45212556587325203
epoch64/100=> train loss = 0.35434632205356986 & vall loss = 0.45040938191943697
epoch65/100=> train loss = 0.3516537581628325 & vall loss = 0.45300698412789236
epoch66/100=> train loss = 0.3524837052754763 & vall loss = 0.45638535022735593
epoch67/100=> train loss = 0.3585030886076264 & vall loss = 0.4517078929477268
epoch68/100=> train loss = 0.35460399175431095 & vall loss = 0.45505036579238045
epoch69/100=> train loss = 0.35079891516663936 & vall loss = 0.4552822921011183
epoch70/100=> train loss = 0.3493703266153228 & vall loss = 0.4551447153091431
epoch71/100=> train loss = 0.3467882781547342 & vall loss = 0.4567027085357242
epoch72/100=> train loss = 0.3519528138603868 & vall loss = 0.464914999405543
epoch73/100=> train loss = 0.34840330018498805 & vall loss = 0.45891080035103693
epoch74/100=> train loss = 0.3494120806792362 & vall loss = 0.45480237205823265
epoch75/100=> train loss = 0.3462683988661416 & vall loss = 0.46387384600109527
epoch76/100=> train loss = 0.3447126168652443 & vall loss = 0.4657014078564114
epoch77/100=> train loss = 0.34804924021838074 & vall loss = 0.4611950165695614
epoch78/100=> train loss = 0.3451053301493327 & vall loss = 0.4620448456870185
epoch79/100=> train loss = 0.3428204812235751 & vall loss = 0.4615623560216692
epoch80/100=> train loss = 0.3402541213284778 & vall loss = 0.4610055042637719
epoch81/100=> train loss = 0.3403893359805231 & vall loss = 0.4602961983945635
epoch82/100=> train loss = 0.3400752894622458 & vall loss = 0.46280412475268046
epoch83/100=> train loss = 0.34035083836754837 & vall loss = 0.4617114126682281
epoch84/100=> train loss = 0.3434339915796862 & vall loss = 0.4742292066415151
epoch85/100=> train loss = 0.34622492780119685 & vall loss = 0.46797683040301
epoch86/100=> train loss = 0.3429817369597106 & vall loss = 0.46661159528626334
epoch87/100=> train loss = 0.33804009063432444 & vall loss = 0.4704589320553674
epoch88/100=> train loss = 0.33844668742290324 & vall loss = 0.4671476721763611
epoch89/100=> train loss = 0.34193929853075644 & vall loss = 0.4678769138124254
epoch90/100=> train loss = 0.3369952843519254 & vall loss = 0.49120258622699314
epoch91/100=> train loss = 0.3370292580733865 & vall loss = 0.4700576000743442
epoch92/100=> train loss = 0.33628495715263873 & vall loss = 0.47620083689689635
epoch93/100=> train loss = 0.34199863950074727 & vall loss = 0.4772835307651096
epoch94/100=> train loss = 0.33370147687567153 & vall loss = 0.49253902832667035
epoch95/100=> train loss = 0.33543383974139973 & vall loss = 0.4768553892771403
epoch96/100=> train loss = 0.333938209182125 & vall loss = 0.47799911432796055
epoch97/100=> train loss = 0.3332357001675051 & vall loss = 0.47032093405723574
epoch98/100=> train loss = 0.3342655306145296 & vall loss = 0.4798259112570021
epoch99/100=> train loss = 0.33896815208560327 & vall loss = 0.4726847496297624
epoch100/100=> train loss = 0.33190190350100146 & vall loss = 0.4717878090010749

In [55]:
# save model parameter
best_val_loss = float("inf")
if epoch_val_loss < best_val_loss:
  best_val_loss = epoch_val_loss
  torch.save(model.state_dict(),"best_model.pt")

In [56]:
torch.load("best_model.pt")
model.load_state_dict(torch.load("best_model.pt"))

In [59]:
# evaluatyion step
model.eval()
with torch.no_grad():
    train_probs = torch.sigmoid(model(X_train_tensor))
    test_probs = torch.sigmoid(model(X_test_tensor))

train_pred = (train_probs >= 0.5).int().numpy()
test_pred = (test_probs >= 0.5).int().numpy()

print("Train accuracy:", accuracy_score(y_train, train_pred))
print("Test accuracy:", accuracy_score(y_test, test_pred))
print(confusion_matrix(y_test, test_pred))
print(classification_report(y_test, test_pred))

Train accuracy: 0.8500177493787717
Test accuracy: 0.7920511000709723
[[920 116]
 [177 196]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.86      1036
           1       0.63      0.53      0.57       373

    accuracy                           0.79      1409
   macro avg       0.73      0.71      0.72      1409
weighted avg       0.78      0.79      0.79      1409